%{
    #include <cstring>
    
    #include "conf_file_parser.hpp"
        
    int current_line_number = 1, current_column_number = 1;
%}

%option nounput
%option noyywrap

%%

\n { current_line_number++; current_column_number = 1; }
[ \t] { current_column_number++; }

[A-Za-z0-9\-\/\.]* { yylval.string = strdup(yytext); current_column_number += strlen(yytext); return WORD; }
. { current_column_number++; return (int) yytext[0]; }


%%
